{% set name = "prepDyn" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dnakamuraz/prepDyn/archive/refs/tags/v0.6.0.tar.gz
  sha256: 6c4e53d612a9a88205ec9480378666690bac74f314f9b3e56ad5e755b114775c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - prepDyn=prepDyn:main
    - GB2MSA=GB2MSA:main
    - addSeq=addSeq:main
    - UP2AP=UP2AP:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - biopython
    - matplotlib-base
    - numpy
    - termcolor
    - mafft

test:
  imports:
    - prepDyn_auxiliary
    - GB2MSA
    - addSeq
    - UP2AP
    - prepDyn
  commands:
    - prepDyn --help
    - GB2MSA --help
    - addSeq --help
    - UP2AP --help

about:
  home: https://github.com/dnakamuraz/PrepDyn
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Preprocessing toolkit for dynamic homology datasets
  dev_url: https://github.com/dnakamuraz/PrepDyn

extra:
  recipe-maintainers:
    - dnakamuraz
