Job Id: 23212.ace
    Job_Name = v5.3.3_PhyG_prepDyn
    Job_Owner = nakamura@ace
    resources_used.cpupercent = 0
    resources_used.cput = 00:00:00
    resources_used.mem = 0kb
    resources_used.ncpus = 64
    resources_used.vmem = 0kb
    resources_used.walltime = 00:00:00
    job_state = R
    queue = workq
    server = ace
    Checkpoint = u
    ctime = Tue Oct 21 18:21:48 2025
    Error_Path = ace:/home/nakamura/B4_prepDyn/empirical3_Nakamura2/5_equal/rou
	nd3/v5.3.3_PhyG_prepDyn.e
    exec_host = no7/0*64
    exec_vnode = (no7:ncpus=64)
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = a
    mtime = Tue Oct 21 18:21:49 2025
    Output_Path = ace:/home/nakamura/B4_prepDyn/empirical3_Nakamura2/5_equal/ro
	und3/v5.3.3_PhyG_prepDyn.o
    Priority = 0
    qtime = Tue Oct 21 18:21:48 2025
    Rerunable = False
    Resource_List.mpiprocs = 64
    Resource_List.ncpus = 64
    Resource_List.nodect = 1
    Resource_List.place = scatter
    Resource_List.select = 1:ncpus=64:mpiprocs=64
    Resource_List.walltime = 1000:00:00
    stime = Tue Oct 21 18:21:49 2025
    session_id = 46874
    jobdir = /home/nakamura
    substate = 42
    Variable_List = PBS_O_HOME=/home/nakamura,PBS_O_LANG=pt_BR.UTF-8,
	PBS_O_LOGNAME=nakamura,
	PBS_O_PATH=/home/sw/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/lo
	cal/sbin:/usr/sbin:/opt/pbs/bin:/home/sw/anaconda3/bin/:/home/nakamura/
	.local/bin:/home/nakamura/bin,PBS_O_MAIL=/var/spool/mail/nakamura,
	PBS_O_SHELL=/bin/bash,
	PBS_O_WORKDIR=/home/nakamura/B4_prepDyn/empirical3_Nakamura2/5_equal/r
	ound3,PBS_O_SYSTEM=Linux,LC_PAPER=pt_BR,MANPATH=:/opt/pbs/share/man,
	XDG_SESSION_ID=3964,LC_ADDRESS=pt_BR,HOSTNAME=ace,LC_MONETARY=pt_BR,
	SELINUX_ROLE_REQUESTED=,
	__LMOD_REF_COUNT_MODULEPATH=/opt/ohpc/pub/modulefiles:1,
	TERM=xterm-256color,SHELL=/bin/bash,LMOD_ROOT=/opt/ohpc/admin/lmod,
	HISTSIZE=1000,SSH_CLIENT=192.168.32.43 43632 22,CONDA_SHLVL=0,
	SELINUX_USE_CURRENT_RANGE=,LMOD_PKG=/opt/ohpc/admin/lmod/lmod,
	LC_NUMERIC=pt_BR,LMOD_VERSION=8.1.18,SSH_TTY=/dev/pts/0,USER=nakamura,
	LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38
	;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5
	;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;
	5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15
	:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=3
	8;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9
	:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;
	5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=
	38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:
	*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=
	38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;
	9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.g
	if=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tg
	a=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.pn
	g=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mo
	v=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.we
	bm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.v
	ob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=
	38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=
	38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;
	5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5
	;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;
	45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;
	45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45
	:*.xspf=38;5;45:,LC_TELEPHONE=pt_BR,
	CONDA_EXE=/home/sw/anaconda3/bin/conda,_CE_CONDA=,
	LMOD_PREPEND_BLOCK=normal,
	_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1a
	WxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5
	PXt9LG1UPXt9LG1wYXRoQT17Ii9vcHQvb2hwYy9wdWIvbW9kdWxlZmlsZXMiLH0sWyJzeXN
	0ZW1CYXNlTVBBVEgiXT0iL29wdC9vaHBjL3B1Yi9tb2R1bGVmaWxlcyIsfQ==,
	MAIL=/var/spool/mail/nakamura,
	PATH=/home/sw/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sb
	in:/usr/sbin:/opt/pbs/bin:/home/sw/anaconda3/bin/:/home/nakamura/.local
	/bin:/home/nakamura/bin,LMOD_SETTARG_CMD=:,LC_IDENTIFICATION=pt_BR,
	PWD=/home/nakamura/B4_prepDyn/empirical3_Nakamura2/5_equal/round3,
	LANG=pt_BR.UTF-8,MODULEPATH=/opt/ohpc/pub/modulefiles,
	_ModuleTable_Sz_=1,LC_MEASUREMENT=pt_BR,SELINUX_LEVEL_REQUESTED=,
	LMOD_CMD=/opt/ohpc/admin/lmod/lmod/libexec/lmod,_CE_M=,
	HISTCONTROL=ignoredups,SHLVL=1,HOME=/home/nakamura,
	BASH_ENV=/opt/ohpc/admin/lmod/lmod/init/bash,
	CONDA_PYTHON_EXE=/home/sw/anaconda3/bin/python,LOGNAME=nakamura,
	SSH_CONNECTION=192.168.32.43 43632 192.168.34.1 22,LC_CTYPE=UTF-8,
	MODULESHOME=/opt/ohpc/admin/lmod/lmod,LMOD_SETTARG_FULL_SUPPORT=no,
	LESSOPEN=||/usr/bin/lesspipe.sh %s,LMOD_FULL_SETTARG_SUPPORT=no,
	XDG_RUNTIME_DIR=/run/user/1007,
	LMOD_DIR=/opt/ohpc/admin/lmod/lmod/libexec,LC_TIME=pt_BR,
	LMOD_COLORIZE=no,LC_NAME=pt_BR,
	BASH_FUNC_module()=() {  eval $($LMOD_CMD bash \"$@\") && eval $(${LMO
	D_SETTARG_CMD:-:} -s sh)
},
	BASH_FUNC_ml()=() {  eval $($LMOD_DIR/ml_cmd \"$@\")
},
	_=/opt/pbs/bin/qsub,
	OLDPWD=/home/nakamura/B4_prepDyn/empirical3_Nakamura2/6_max,
	PBS_O_QUEUE=workq,PBS_O_HOST=ace
    comment = Job run at Tue Oct 21 at 18:21 on (no7:ncpus=64)
    etime = Tue Oct 21 18:21:48 2025
    run_count = 1
    Submit_arguments = v5.3.3_PHYG.pbs
    project = _pbs_project_default

